kind: live
title: Taxi Tips

defaults:
  life_span: 3d

images:
  myimage:
    ref: image:$[[ flow.project_id ]]:v1
    dockerfile: $[[ flow.workspace ]]/Dockerfile
    context: $[[ flow.workspace ]]/
    build_preset: cpu-large

volumes:
  data:
    remote: storage:$[[ flow.project_id ]]/data
    mount: /project/data
    local: data
  code:
    remote: storage:$[[ flow.project_id ]]/modules
    mount: /project/modules
    local: modules
  notebooks:
    remote: storage:$[[ flow.project_id ]]/notebooks
    mount: /project/notebooks
    local: notebooks
  results:
    remote: storage:$[[ flow.project_id ]]/results
    mount: /project/results
    local: results
  project:
    remote: storage:$[[ flow.project_id ]]
    mount: /project
    local: .

jobs:
  download_data:
    image: neuromation/neuro-extras:latest
    volumes:
      - $[[ volumes.data.ref ]]
    preset: cpu-small
    bash: |
      cd $[[ volumes.data.mount ]]
      for month in $(seq -w 1 12)
      do
        curl https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2020-${month}.csv -o data-${month}.csv
      done

  inference:
    image: $[[ images.myimage.ref ]]
    life_span: 10d
    http_port: 8000
    http_auth: False
    volumes:
      - $[[ upload(volumes.code).ref_ro ]]
      - $[[ volumes.results.ref_ro ]]
    env:
      EXPOSE_SSH: "yes"
      PYTHONPATH: $[[ volumes.code.mount ]]
    bash: |
        cd $[[ volumes.project.mount ]]
        uvicorn modules.infer:app

  jupyter:
    action: gh:neuro-actions/jupyter@v1.0.0
    args:
      image: $[[ images.myimage.ref ]]
      preset: cpu-large
      volumes_data_remote: $[[ volumes.data.remote ]]
      volumes_code_remote: $[[ volumes.code.remote ]]
      volumes_config_remote: $[[ volumes.config.remote ]]
      volumes_notebooks_remote: $[[ volumes.notebooks.remote ]]
      volumes_results_remote: $[[ volumes.results.remote ]]

  filebrowser:
    action: gh:neuro-actions/filebrowser@v1.0.0
    args:
      volumes_project_remote: $[[ volumes.project.remote ]]

  locust:
    image: locustio/locust:1.4.1
    name: $[[ flow.title ]]-locust
    http_port: 8080
    http_auth: False
    life_span: 1d
    detach: True
    browse: True
    params:
      # https://open-source-stack-test-inference--yevheniisemendiak.jobs.neuro-compute.org.neu.ro/predict
      # https://seldon.onprem-poc.org.neu.ro/seldon/seldon/my-model/api/v1.0/predictions
      endpoint_url:
    volumes:
      - $[[ upload(volumes.code).ref_ro ]]
    env:
      PYTHONPATH: $[[ volumes.src.mount ]]/..
    cmd: |
      -f $[[ volumes.code.mount ]]/locust.py --web-port 8080 -H $[[ params.endpoint_url ]]